#manish.n.manish45@gmail.com add at 20151108 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += ili9881_dsi_hd720_txd_zaw809.o

#manish.n.manish45@gmail..com add at 20151108 end
