#manish.n.manish45@gmail.com add at 20151108 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
obj-y   +=  ili9881_dsi_hd720_txd_zaw809.o

#manish.n.manish45@gmail..com add at 20151108 end
